### ISSUE TITLE
-bash: lein: command not found

### ISSUE THREAD

**Issue by xuanus** [sharetribe/harmony#41]
Run "DB_PORT=13306 lein migrate migrate"
Get "-bash: lein: command not found"

Would be helpful, if adding lein installation steps/link in README
http://www.lispcast.com/clojure-mac
https://gist.github.com/technomancy/2395913

**Comment by alexey** [comment]
For ubuntu use https://leiningen.org/#install and you are good

**Comment by pcm211** [comment]
@alexey thank you ... for this and btw did you manage availability with stripe ?

**Comment by pcm211** [comment]
@xuanus DB_PORT=13306 lein migrate migrate  still is unable to locate lein even after installation ... could you give an insight as u must have burnt a lot of midnight oil ....me trying it since 2 days :)
