### ISSUE TITLE
Running without docket or convox

### ISSUE THREAD

**Issue by alexey** [sharetribe/harmony#43]
Hello,

I am trying to run on clean ubuntu server and its not going with lein.

Can you please be so kind and post shorty instruction for how to do it ?

Thanks in advance

**Comment by zenikk** [comment]
To build jar:
```lein clean && lein uberjar```
To run server:
```HARMONY_JAVA_OPTS="-server -Xms256m -Xmx768m -Xss512k -XX:+UseG1GC"
AUTH_TOKEN_SECRETS=SECRET_TOKEN111 DB_PORT=13306 java $HARMONY_JAVA_OPTS -cp target/sharetribe-harmony.jar clojure.main -m harmony.main.harmony-api
```
You can override config settings with env variables, see resources/conf/harmony-api.edn

**Comment by alexey** [comment]
Thank you ! 
I did the same by reading docker files better
